import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Timestamp Microservice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Timestamp Microservice</h1>
      <hr />
      <div className="container">
        <h3>Example Usage:</h3>
        <ul>
          <li>
            <a href="api/2015-12-25">[project url]/api/2015-12-25</a>
          </li>
          <li>
            <a href="api/1451001600000">[project url]/api/1451001600000</a>
          </li>
        </ul>

        <h3>Example Output:</h3>
        <p>
          <code>
            {"{ unix: 1451001600000, utc: 'Fri, 25 Dec 2015 00:00:00 GMT' }"}
          </code>
        </p>
      </div>
      <div className="footer">
        <p>
          <a href="https://github.com/alistairvu/timestamp-microservice">
            GitHub
          </a>
        </p>
      </div>
    </div>
  );
};

export default Home;
